# Theme settings
doks:
    baseurl:
    color_theme:
    header:
        logo:
            text: Fabric Community Wiki
            image:
        nav:
            - item_name: Home
              item_url: '/'  
            - item_name: GitHub
              item_url: 'https://github.com/mineblock11/fabric-community-wiki'
            - item_name: Discord
              item_url: 'https://discord.gg/5tmestARuU'
    footer:
        social_list:   
            - network_name: github
              profile_url: https://github.com/mineblock11/fabric-community-wiki   
            - network_name: discord
              profile_url: https://discord.gg/5tmestARuU
            
        content:
            copyright: 'All pages on this website are licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.<br><small>Not affliated with Fabric Loader</small>'
            
            logo:
                text: Fabric Community Wiki
                image:
                

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true